
version: '3.5'

services:
  postgres:
    image: postgres:11.2-alpine
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      shared_net:
      default:

  kafka:
    image: landoop/kafka-lenses-dev
    env_file:
      - .env.dev
    networks:
      shared_net:
      default:
    ports:
      - 3030:3030
      - 9092:9092
      - 2181:2181
      - 8081:8081
      - 9581:9581
      - 9582:9582
      - 9584:9584
      - 9585:9585

volumes:
  postgres_data:

networks:
  shared_net:
    driver: bridge
  default:
    driver: bridge
