version: '3.5'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    env_file:
      - .env
    networks:
      shared_net:
      default:

networks:
  shared_net:
    driver: bridge
  default:
    driver: bridge
