version: 2

executors:
  web-app:
    docker:
      - image: circleci/node:11.15.0
        environment:
          KAFKA_HOST: localhost:9092
          WEBHOOK_TOPIC_NAME: webhooks
          WEBHOOK_TOPIC_OFFSET: 0
          WEBHOOK_TOPIC_PARTITION: 0
          WEBHOOK_TOPIC_PARTITION_COUNT: 1
          WEBHOOK_TOPIC_REPLICATION_FACTOR: 1
          WEBHOOK_CONSUMER_GROUP_ID: node-webhook-dispatcher

commands:
  prepare-node:
    description: "Install dependencies from cache for web-app"
    steps:
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
jobs:
  integration:
    working_directory: ~/app
    executor: web-app
    docker:
      - image: wurstmeister/zookeeper
      - image: wurstmeister/kafka:2.11-0.11.0.3
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_PORT: 9092
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_DELETE_TOPIC_ENABLE: true
    steps:
      - checkout
      - prepare-node
      - run:
          name: test
          command: npm run test:integration

  unit:
    working_directory: ~/app
    executor: web-app
    steps:
      - checkout
      - prepare-node
      - run:
          name: test
          command: npm run test


workflows:
  version: 2
  test:
    jobs:
      - unit
      - integration
